export const carData = [
  {
    slug: "toyota-alphard-2023",
    name: "Toyota Alphard",
    image: "/armada/Alphard.webp",
    hint: "luxury van executive",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Matic",
    capacity: 6,
    prices: {
      driver: "Hubungi Kami",
    },
    description:
      "Kenyamanan premium untuk perjalanan bisnis, acara spesial, atau liburan keluarga dengan gaya eksekutif.",
    gallery: {
      interior: "/armada/interior/alphard.jpg",
      front: "/armada/front/alphard.jpg",
      back: "/armada/back/alphard.jpg",
    },
    advantages: [
      "Kabin super mewah dengan Captain Seat",
      "Interior senyap dan suspensi nyaman",
      "Fitur keselamatan canggih",
      "Desain eksterior yang prestisius",
    ],
  },
  {
    slug: "hilux-double-cabin-2023",
    name: "Hilux Double Cabin",
    image: "/armada/hilux-double-cabin.webp",
    hint: "pickup truck offroad",
    type: "pickup",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Manual",
    capacity: 5,
    prices: {
      driver: "Hubungi Kami",
    },
    description:
      "Tangguh di segala medan, cocok untuk kebutuhan proyek, survei, atau petualangan di area perkebunan.",
    gallery: {
      interior: "/armada/interior/hilux-double-cabin.jpg",
      front: "/armada/front/hilux-double-cabin.jpg",
      back: "/armada/back/hilux-double-cabin.jpg",
    },
    advantages: [
      "Kemampuan off-road yang luar biasa",
      "Bak angkut barang yang luas dan fungsional",
      "Kabin ganda untuk penumpang dan barang",
      "Mesin diesel yang kuat untuk medan berat",
    ],
  },
  {
    slug: "hiace-premio-luxury",
    name: "Hiace Premio Luxury",
    image: "/armada/hiace-premio-luxury.webp",
    hint: "luxury minibus vip",
    type: "minibus",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Manual",
    capacity: 9,
    prices: {
      driver: "Hubungi Kami",
    },
    description:
      "Minibus mewah dengan interior captain seat, cocok untuk perjalanan VIP dan group tour premium.",
    gallery: {
      interior: "/armada/interior/hiace-premio-luxury.jpg",
      front: "/armada/front/hiace-premio-luxury.jpg",
      back: "/armada/back/hiace-premio-luxury.jpg",
    },
    advantages: [
      "Kabin mewah dengan captain seat",
      "Fasilitas premium untuk kenyamanan maksimal",
      "Ruang kabin yang sangat luas",
      "Cocok untuk perjalanan bisnis dan pariwisata VIP",
    ],
  },
  {
    slug: "hiace-premio",
    name: "Hiace Premio",
    image: "/armada/hiace-premio.webp",
    hint: "minibus premium group",
    type: "minibus",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Manual",
    capacity: 12,
    prices: {
      driver: "Hubungi Kami",
    },
    description:
      "Kenyamanan dan gaya premium untuk perjalanan grup. Lebih modern dan eksklusif dari Commuter.",
    gallery: {
      interior: "/armada/interior/hiace-premio-luxury.jpg",
      front: "/armada/front/hiace-premio-luxury.jpg",
      back: "/armada/back/hiace-premio-luxury.jpg",
    },
    advantages: [
      "Desain eksterior dan interior yang lebih modern",
      "Kenyamanan penumpang yang ditingkatkan",
      "Kapasitas besar untuk grup",
      "Mesin bertenaga untuk perjalanan jauh",
    ],
  },
  {
    slug: "hiace-commuter",
    name: "Hiace Commuter",
    image: "/armada/hiace-commuter.webp",
    hint: "standard minibus tour",
    type: "minibus",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Manual",
    capacity: 15,
    prices: {
      driver: "Hubungi Kami",
    },
    description:
      "Solusi transportasi andal untuk grup besar, tour, atau acara perusahaan. Kapasitas maksimal, tetap nyaman.",
    gallery: {
      interior: "/armada/interior/hiace-commuter.jpg",
      front: "/armada/front/hiace-commuter.jpg",
      back: "/armada/back/hiace-commuter.jpg",
    },
    advantages: [
      "Kapasitas penumpang hingga 15 orang",
      "Sangat andal untuk perjalanan jarak jauh",
      "Ruang bagasi yang luas",
      "Biaya operasional efisien untuk perjalanan grup",
    ],
  },
  {
    slug: "isuzu-elf-minibus",
    name: "Isuzu Elf Minibus",
    image: "/armada/isuzu-elf-minibus.webp",
    hint: "large minibus rombongan",
    type: "minibus",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Manual",
    capacity: 18,
    prices: {
      driver: "Hubungi Kami",
    },
    description:
      "Pilihan utama untuk rombongan wisata atau keluarga besar dengan kapasitas hingga 18 penumpang.",
    gallery: {
      interior: "/armada/interior/isuzu-elf-minibus.jpg",
      front: "/armada/front/isuzu-elf-minibus.jpg",
      back: "/armada/back/isuzu-elf-minibus.jpg",
    },
    advantages: [
      "Daya angkut penumpang terbesar",
      "Mesin diesel tangguh dan irit",
      "Chassis kuat dan durabilitas teruji",
      "Fleksibel untuk berbagai kebutuhan perjalanan grup",
    ],
  },
  {
    slug: "toyota-fortuner-2023",
    name: "Toyota Fortuner",
    image: "/armada/fortuner.webp",
    hint: "powerful suv premium",
    type: "suv",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Matic",
    capacity: 7,
    prices: {
      matic: "Rp 800.000",
    },
    description:
      "SUV premium dengan performa tangguh dan tampilan maskulin, cocok untuk perjalanan bisnis maupun liburan.",
    gallery: {
      interior: "/armada/interior/fortuner.jpg",
      front: "/armada/front/fortuner.jpg",
      back: "/armada/back/fortuner.jpg",
    },
    advantages: [
      "Desain eksterior yang gagah dan mewah",
      "Performa mesin diesel yang kuat dan andal",
      "Kabin nyaman dengan fitur modern",
      "Reputasi brand Toyota yang terjamin",
    ],
  },
  {
    slug: "mitsubishi-pajero-2023",
    name: "Mitsubishi Pajero",
    image: "/armada/pajero.webp",
    hint: "suv adventure tangguh",
    type: "suv",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Matic",
    capacity: 7,
    prices: {
      matic: "Rp 750.000",
    },
    description:
      "SUV tangguh yang siap untuk petualangan Anda di segala medan, baik dalam kota maupun off-road ringan.",
    gallery: {
      interior: "/armada/interior/pajero.jpg",
      front: "/armada/front/pajero.jpg",
      back: "/armada/back/pajero.jpg",
    },
    advantages: [
      "Performa mesin diesel yang bertenaga",
      "Ground clearance tinggi, siap segala medan",
      "Kabin luas untuk 7 penumpang",
      "Tampilan gagah dan sporty",
    ],
  },
  {
    slug: "innova-zenix-2024",
    name: "Innova Zenix",
    image: "/armada/zenix.webp",
    hint: "hybrid crossover modern",
    type: "crossover",
    year: "2023 - 2025",
    fuel: "Hybrid/Bensin",
    transmission: "Matic",
    capacity: 7,
    prices: {
      matic: "Rp 700.000",
    },
    description:
      "Crossover mewah dengan pilihan mesin hybrid yang efisien. Tingkat kenyamanan baru untuk keluarga modern.",
    gallery: {
      interior: "/armada/interior/innova-zenix.jpg",
      front: "/armada/front/innova-zenix.jpg",
      back: "/armada/back/innova-zenix.jpg",
    },
    advantages: [
      "Tersedia varian Hybrid yang sangat irit BBM",
      "Kenyamanan setara MPV mewah",
      "Desain crossover yang modern dan gagah",
      "Fitur keselamatan Toyota Safety Sense (TSS)",
    ],
  },
  {
    slug: "innova-reborn-2023",
    name: "Innova Reborn",
    image: "/armada/reborn.webp",
    hint: "family suv diesel",
    type: "suv",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 550.000",
      matic: "Rp 600.000",
    },
    description:
      "Kenyamanan legendaris Kijang Innova yang tak tertandingi, pilihan utama untuk keluarga dan bisnis.",
    gallery: {
      interior: "/armada/interior/reborn.jpg",
      front: "/armada/front/reborn.jpg",
      back: "/armada/back/reborn.jpg",
    },
    advantages: [
      "Durabilitas dan keandalan teruji",
      "Kabin lapang dan nyaman untuk 7 orang",
      "Perawatan mudah dan suku cadang melimpah",
      "Nilai jual kembali yang tinggi",
    ],
  },
  {
    slug: "grand-innova-diesel-2015",
    name: "Grand Innova Diesel",
    image: "/armada/innova-diesel.webp",
    hint: "reliable diesel irit",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Diesel",
    transmission: "Manual",
    capacity: 7,
    prices: {
      manual: "Rp 450.000",
    },
    description:
      "Mesin diesel legendaris yang tangguh dan irit. Pilihan ekonomis untuk perjalanan jauh yang andal.",
    gallery: {
      interior: "/armada/interior/innova-diesel.jpg",
      front: "/armada/front/innova-diesel.jpg",
      back: "/armada/back/innova-diesel.jpg",
    },
    advantages: [
      "Mesin diesel D-4D yang sangat tangguh dan irit",
      "Biaya sewa lebih ekonomis",
      "Kapasitas angkut yang besar dan handal",
      "Perawatan mudah dan murah",
    ],
  },
  {
    slug: "rush-2023",
    name: "Toyota Rush",
    image: "/armada/toyota-rush.webp",
    hint: "reliable suv family",
    type: "suv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 400.000",
      matic: "Rp 450.000",
    },
    description:
      "Saudara kembar Terios dengan sentuhan desain dan brand Toyota yang terpercaya.",
    gallery: {
      interior: "/armada/interior/rush.jpg",
      front: "/armada/front/rush.jpg",
      back: "/armada/back/rush.jpg",
    },
    advantages: [
      "Build quality khas Toyota",
      "Jaringan servis yang sangat luas",
      "Kabin nyaman dan fungsional",
      "Desain yang tangguh dan elegan",
    ],
  },
  {
    slug: "terios-2023",
    name: "Daihatsu Terios",
    image: "/armada/terios.webp",
    hint: "adventure suv 7-seater",
    type: "suv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 400.000",
      matic: "Rp 450.000",
    },
    description:
      "SUV 7-seater dengan ground clearance tinggi, siap menemani petualangan keluarga Anda.",
    gallery: {
      interior: "/armada/interior/terios.jpg",
      front: "/armada/front/terios.jpg",
      back: "/armada/back/terios.jpg",
    },
    advantages: [
      "Ground clearance tinggi, lebih percaya diri",
      "Kabin luas untuk 7 penumpang",
      "Fitur keamanan yang lengkap di kelasnya",
      "Tampilan sporty dan modern",
    ],
  },
  {
    slug: "suzuki-xl7-2023",
    name: "Suzuki XL7",
    image: "/armada/suzuki-xl7.webp",
    hint: "crossover suv modern",
    type: "crossover",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 400.000",
      matic: "Rp 450.000",
    },
    description:
      "Crossover tangguh dengan fitur canggih seperti Smart E-Mirror, memberikan kenyamanan dan gaya.",
    gallery: {
      interior: "/armada/interior/suzuki-xl7.jpg",
      front: "/armada/front/suzuki-xl7.jpg",
      back: "/armada/back/suzuki-xl7.jpg",
    },
    advantages: [
      "Desain Crossover SUV yang gagah",
      "Kabin yang lega dan nyaman",
      "Irit bahan bakar",
      "Fitur modern seperti Smart E-Mirror",
    ],
  },
  {
    slug: "mitsubishi-xpander-2023",
    name: "Mitsubishi Xpander",
    image: "/armada/xpander.webp",
    hint: "family mpv nyaman",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 400.000",
      matic: "Rp 450.000",
    },
    description:
      "MPV keluarga yang nyaman, irit, dan serbaguna. Pilihan tepat untuk perjalanan dalam dan luar kota.",
    gallery: {
      interior: "/armada/interior/xpander.jpg",
      front: "/armada/front/xpander.jpg",
      back: "/armada/back/xpander.jpg",
    },
    advantages: [
      "Kabin paling senyap di kelasnya",
      "Suspensi nyaman khas Xpander",
      "Efisiensi bahan bakar yang baik",
      "Desain modern dan futuristik",
    ],
  },
  {
    slug: "all-new-avanza-2023",
    name: "All New Avanza",
    image: "/armada/All-new-avanza.webp",
    hint: "modern mpv irit",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 350.000",
      matic: "Rp 400.000",
    },
    description:
      "Generasi terbaru Avanza dengan penggerak roda depan, lebih nyaman dan modern.",
    gallery: {
      interior: "/armada/interior/all-new-avanza.jpg",
      front: "/armada/front/all-new-avanza.jpg",
      back: "/armada/back/all-new-avanza.jpg",
    },
    advantages: [
      "Kenyamanan suspensi yang jauh lebih baik",
      "Kabin lebih modern dengan fitur baru",
      "Efisiensi bahan bakar yang optimal",
      "Dilengkapi fitur keselamatan canggih (TSS)",
    ],
  },
  {
    slug: "daihatsu-xenia-2023",
    name: "Daihatsu Xenia",
    image: "/armada/xenia.webp",
    hint: "reliable mpv keluarga",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 350.000",
      matic: "Rp 400.000",
    },
    description:
      "Pilihan ekonomis dan handal untuk keluarga maupun perjalanan grup dengan kapasitas 7 penumpang.",
    gallery: {
      interior: "/armada/interior/xenia.jpg",
      front: "/armada/front/xenia.jpg",
      back: "/armada/back/xenia.jpg",
    },
    advantages: [
      "Biaya sewa dan operasional ekonomis",
      "Kabin fleksibel dengan kursi baris ketiga",
      "Jaringan servis luas di seluruh Indonesia",
      "Fitur keamanan dasar yang lengkap",
    ],
  },
  {
    slug: "suzuki-ertiga-hybrid-2023",
    name: "Suzuki Ertiga Hybrid",
    image: "/armada/ertiga-hybrid.webp",
    hint: "hybrid mpv irit",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Hybrid",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 400.000",
      matic: "Rp 450.000",
    },
    description:
      "MPV keluarga dengan teknologi mild hybrid, memberikan efisiensi bahan bakar yang lebih baik.",
    gallery: {
      interior: "/armada/interior/ertiga-hybrid.jpg",
      front: "/armada/front/ertiga-hybrid.jpg",
      back: "/armada/back/ertiga-hybrid.jpg",
    },
    advantages: [
      "Teknologi Smart Hybrid untuk efisiensi BBM",
      "Fitur cruise control untuk kenyamanan berkendara",
      "Kabin yang nyaman dan fungsional",
      "Biaya operasional yang rendah",
    ],
  },
  {
    slug: "suzuki-ertiga-2022",
    name: "Suzuki Ertiga",
    image: "/armada/ertiga.webp",
    hint: "spacious mpv nyaman",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 350.000",
      matic: "Rp 400.000",
    },
    description:
      "Kabin yang luas dengan kenyamanan ekstra untuk penumpang, ideal untuk perjalanan jauh.",
    gallery: {
      interior: "/armada/interior/ertiga.jpg",
      front: "/armada/front/ertiga.jpg",
      back: "/armada/back/ertiga.jpg",
    },
    advantages: [
      "Kenyamanan kursi penumpang terbaik di kelasnya",
      "Konsumsi BBM yang efisien",
      "Fitur AC double blower hingga baris belakang",
      "Ruang bagasi yang akomodatif",
    ],
  },
  {
    slug: "toyota-calya-2023",
    name: "Toyota Calya",
    image: "/armada/calya.webp",
    hint: "compact mpv lcgc",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 300.000",
      matic: "Rp 350.000",
    },
    description:
      "Mobil LCGC 7-seater yang irit dan praktis untuk kebutuhan transportasi keluarga di dalam kota.",
    gallery: {
      interior: "/armada/interior/calya.jpg",
      front: "/armada/front/calya.jpg",
      back: "/armada/back/calya.jpg",
    },
    advantages: [
      "Sangat irit bahan bakar",
      "Kapasitas 7 penumpang dengan harga terjangkau",
      "Praktis untuk mobilitas perkotaan",
      "Biaya perawatan yang ekonomis",
    ],
  },
  {
    slug: "daihatsu-sigra-2023",
    name: "Daihatsu Sigra",
    image: "/armada/sigra.webp",
    hint: "affordable mpv ekonomis",
    type: "mpv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Manual & Matic",
    capacity: 7,
    prices: {
      manual: "Rp 300.000",
      matic: "Rp 350.000",
    },
    description:
      "Pilihan paling ekonomis untuk mobil 7-seater, handal untuk penggunaan harian.",
    gallery: {
      interior: "/armada/interior/sigra.jpg",
      front: "/armada/front/sigra.jpg",
      back: "/armada/back/sigra.jpg",
    },
    advantages: [
      "Harga sewa paling terjangkau di kelas 7-seater",
      "Irit bahan bakar",
      "Kabin yang cukup lega untuk kelasnya",
      "Perawatan mudah dan murah",
    ],
  },
  {
    slug: "toyota-raize-2024",
    name: "Toyota Raize",
    image: "/armada/raize.webp",
    hint: "sporty compact suv turbo",
    type: "suv",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Matic",
    capacity: 5,
    prices: {
      matic: "Rp 400.000",
    },
    description:
      "SUV compact dengan gaya sporty dan fitur modern, cocok untuk jiwa muda yang dinamis.",
    gallery: {
      interior: "/armada/interior/raize.jpg",
      front: "/armada/front/raize.jpg",
      back: "/armada/back/raize.jpg",
    },
    advantages: [
      "Mesin turbo yang responsif dan bertenaga",
      "Fitur keselamatan Toyota Safety Sense (TSS)",
      "Desain two-tone yang stylish",
      "Praktis untuk penggunaan perkotaan",
    ],
  },
  {
    slug: "honda-brio-2024",
    name: "Honda Brio",
    image: "/armada/brio.webp",
    hint: "compact city car lincah",
    type: "hatchback",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Matic",
    capacity: 5,
    prices: {
      matic: "Rp 350.000",
    },
    description:
      "Mobil kota yang lincah, irit, dan stylish. Sempurna untuk mobilitas harian Anda di perkotaan.",
    gallery: {
      interior: "/armada/interior/brio.jpg",
      front: "/armada/front/brio.jpg",
      back: "/armada/back/brio.jpg",
    },
    advantages: [
      "Sangat irit bahan bakar",
      "Handling lincah dan mudah diparkir",
      "Desain sporty dan modern",
      "Performa mesin responsif untuk dalam kota",
    ],
  },
  {
    slug: "toyota-agya-2023",
    name: "Toyota Agya",
    image: "/armada/agya.webp",
    hint: "city hatchback sporty",
    type: "hatchback",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Matic",
    capacity: 5,
    prices: {
      matic: "Rp 325.000",
    },
    description:
      "City car handal dengan sentuhan sporty, lincah untuk menembus padatnya lalu lintas kota.",
    gallery: {
      interior: "/armada/interior/agya.jpg",
      front: "/armada/front/agya.jpg",
      back: "/armada/back/agya.jpg",
    },
    advantages: [
      "Model terbaru dengan desain lebih sporty",
      "Sangat irit dan mudah perawatannya",
      "Lincah dan gesit untuk penggunaan dalam kota",
      "Brand Toyota yang terjamin kualitasnya",
    ],
  },
  {
    slug: "daihatsu-ayla-2023",
    name: "Daihatsu Ayla",
    image: "/armada/ayla.webp",
    hint: "economic hatchback murah",
    type: "hatchback",
    year: "2023 - 2025",
    fuel: "Bensin",
    transmission: "Matic",
    capacity: 5,
    prices: {
      matic: "Rp 325.000",
    },
    description:
      "Pilihan paling ekonomis untuk mobil kota yang lincah dan sangat irit bahan bakar.",
    gallery: {
      interior: "/armada/interior/ayla.jpg",
      front: "/armada/front/ayla.jpg",
      back: "/armada/back/ayla.jpg",
    },
    advantages: [
      "Sangat efisien dalam konsumsi bahan bakar",
      "Biaya sewa yang sangat terjangkau",
      "Ukuran compact, mudah untuk parkir",
      "Perawatan yang simpel dan murah",
    ],
  },
];
